In [1]:
import numpy as np

In [14]:
'''
二进制格式保存和存取文件
np.save():自动保存的文件后缀名是.npy
np.load(),

'''
#保存
x = np.arange(10)
np.save('local_text',x)
#读取
load = np.load('local_text.npy')
# 可以将多个数组压缩到一个文件,此时存贮的是key-value 对，key我们制定，value就是要保存的数据=>np.savez(),后缀名是.npz
y = np.arange(10,20)
np.savez('local_text.npz',a=x,b=y)
load = np.load('local_text.npz')
print load['a']
print load['b']

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [32]:
'''
Numpy.linalg 包中的常用函数：
diag(),dot(),trace(),det(),eig(),inv(),
pinv(): 矩阵的Moore-Penrose 伪逆
qr(0: QR分解
svd(): SVD分解
solve():解决线性方程，其中Ax=B,A为方阵
lstsq(): Ax=b的最小二乘解
'''
import numpy.linalg as lin
A = np.arange(16).reshape(4,4)
print A,'\n'
print lin.svd(A),'\n'
print lin.lstsq(A,np.arange(4)),'\n'
print lin.solve(np.eye(3),np.arange(3)) #注意此时A必须是可逆的

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

(array([[-0.09184212, -0.83160389,  0.53515573,  0.11665482],
       [-0.31812733, -0.44586433, -0.80049034,  0.24334177],
       [-0.54441254, -0.06012478, -0.00448651, -0.836648  ],
       [-0.77069775,  0.32561478,  0.26982112,  0.47665141]]), array([  3.51399637e+01,   2.27661021e+00,   1.69970911e-15,
         8.07447880e-17]), array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
       [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
       [-0.22125808,  0.66846675, -0.67315927,  0.2259506 ],
       [ 0.50104377, -0.50314233, -0.49684666,  0.49894522]])) 

(array([ 0.175,  0.1  ,  0.025, -0.05 ]), array([], dtype=float64), 2, array([  3.51399637e+01,   2.27661021e+00,   1.69970911e-15,
         8.07447880e-17])) 

[ 0.  1.  2.]


In [51]:
'''
numpy.random 的常用函数
permutation(), shuffle(),
rand():均匀分布
randint():给丁上下届范围的整数
randn()：标准正太分布
normal(): 正太分布
beta(), chisquare(),gamma()
'''
import numpy.random as npr
print npr.permutation(np.array([1,2,3,4])),'\n'
print npr.rand(2,6)
print npr.randint(2,10,size=(3,3)) #随机产生一个2～10的整数

[3 4 1 2] 

[[ 0.79704955  0.99052632  0.52892543  0.9958531   0.3648828   0.2692635 ]
 [ 0.46947302  0.28754793  0.15175711  0.23743285  0.54757201  0.51038284]]
[[3 9 6]
 [2 5 5]
 [9 9 3]]
