In [7]:
import numpy as np
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)

In [8]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
# the +,-,*,/ operations are based on each element
print a1+a2
print a1-a2
print a1*a2
print a1/a2

[[ 6  8 10]
 [12 14 16]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 0  7 16]
 [27 40 55]]
[[0 0 0]
 [0 0 0]]


In [17]:
# notice that the type for the data is int,so the division is all 0's

a1.arange(6,dtype=float)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'