In [16]:
import numpy as np
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)

In [3]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
# the +,-,*,/ operations are based on each element
print a1+a2
print a1-a2
print a1*a2
print a1/a2

[[ 6  8 10]
 [12 14 16]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 0  7 16]
 [27 40 55]]
[[0 0 0]
 [0 0 0]]


In [7]:
# auto complete when the size is negative
a1.shape = 2,-1
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
a11=a1.reshape(1,6)
a11[0][0]=100
# share the same memory since the immutable type of the int
print a11
print a1

[[100   1   2   3   4   5]]
[[100   1   2]
 [  3   4   5]]


In [21]:
# initiliza the array with given data type
a=np.array(range(5),dtype=int)
print a

[0 1 2 3 4]


In [26]:
#self define the data type
person = np.dtype({'names':['name','age'],'formats':['S32','i']})
print person
a=np.array([('tom',12)],dtype=person)
print a
print a[0]
print a[0]['name']
print a[0]['age']

[('name', 'S32'), ('age', '<i4')]
[('tom', 12)]
('tom', 12)
tom
12


In [33]:
# dot operation
a = np.arange(12).reshape(2,3,2)
print 'a is:\n'
print a
b = np.arange(12,24).reshape(2,2,3)
print 'b is:\n'
print b
print 'result is:\n'
print np.dot(a,b)#the result is 3*2*3


a is:

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
b is:

[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
result is:

[[[[ 15  16  17]
   [ 21  22  23]]

  [[ 69  74  79]
   [ 99 104 109]]

  [[123 132 141]
   [177 186 195]]]


 [[[177 190 203]
   [255 268 281]]

  [[231 248 265]
   [333 350 367]]

  [[285 306 327]
   [411 432 453]]]]


In [37]:
# innner &outer product
x = np.arange(12).reshape(3,4)
print 'x is:'
print x
y = np.arange(12,24).reshape(3,4)
print 'y is:'
print y

print 'inner result is:'
print np.inner(x,y)
print 'outer result is:'
print np.outer(x,y)


x is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
y is:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
inner result is:
[[ 86 110 134]
 [302 390 478]
 [518 670 822]]
outer result is:
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  26  28  30  32  34  36  38  40  42  44  46]
 [ 36  39  42  45  48  51  54  57  60  63  66  69]
 [ 48  52  56  60  64  68  72  76  80  84  88  92]
 [ 60  65  70  75  80  85  90  95 100 105 110 115]
 [ 72  78  84  90  96 102 108 114 120 126 132 138]
 [ 84  91  98 105 112 119 126 133 140 147 154 161]
 [ 96 104 112 120 128 136 144 152 160 168 176 184]
 [108 117 126 135 144 153 162 171 180 189 198 207]
 [120 130 140 150 160 170 180 190 200 210 220 230]
 [132 143 154 165 176 187 198 209 220 231 242 253]]
