In [1]:
import numpy as np
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)

In [3]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
# the +,-,*,/ operations are based on each element
print a1+a2
print a1-a2
print a1*a2
print a1/a2

[[ 6  8 10]
 [12 14 16]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 0  7 16]
 [27 40 55]]
[[0 0 0]
 [0 0 0]]


In [7]:
# auto complete when the size is negative
a1.shape = 2,-1
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
a11=a1.reshape(1,6)
a11[0][0]=100
# share the same memory since the immutable type of the int
print a11
print a1

[[100   1   2   3   4   5]]
[[100   1   2]
 [  3   4   5]]


In [21]:
# initiliza the array with given data type
a=np.array(range(5),dtype=int)
print a

[0 1 2 3 4]


In [26]:
#self define the data type
person = np.dtype({'names':['name','age'],'formats':['S32','i']})
print person
a=np.array([('tom',12)],dtype=person)
print a
print a[0]
print a[0]['name']
print a[0]['age']

[('name', 'S32'), ('age', '<i4')]
[('tom', 12)]
('tom', 12)
tom
12


In [33]:
# dot operation
a = np.arange(12).reshape(2,3,2)
print 'a is:\n'
print a
b = np.arange(12,24).reshape(2,2,3)
print 'b is:\n'
print b
print 'result is:\n'
print np.dot(a,b)#the result is 3*2*3


a is:

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
b is:

[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
result is:

[[[[ 15  16  17]
   [ 21  22  23]]

  [[ 69  74  79]
   [ 99 104 109]]

  [[123 132 141]
   [177 186 195]]]


 [[[177 190 203]
   [255 268 281]]

  [[231 248 265]
   [333 350 367]]

  [[285 306 327]
   [411 432 453]]]]


In [37]:
# innner &outer product
x = np.arange(12).reshape(3,4)
print 'x is:'
print x
y = np.arange(12,24).reshape(3,4)
print 'y is:'
print y

print 'inner result is:'
print np.inner(x,y)
print 'outer result is:'
print np.outer(x,y)


x is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
y is:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
inner result is:
[[ 86 110 134]
 [302 390 478]
 [518 670 822]]
outer result is:
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  26  28  30  32  34  36  38  40  42  44  46]
 [ 36  39  42  45  48  51  54  57  60  63  66  69]
 [ 48  52  56  60  64  68  72  76  80  84  88  92]
 [ 60  65  70  75  80  85  90  95 100 105 110 115]
 [ 72  78  84  90  96 102 108 114 120 126 132 138]
 [ 84  91  98 105 112 119 126 133 140 147 154 161]
 [ 96 104 112 120 128 136 144 152 160 168 176 184]
 [108 117 126 135 144 153 162 171 180 189 198 207]
 [120 130 140 150 160 170 180 190 200 210 220 230]
 [132 143 154 165 176 187 198 209 220 231 242 253]]


In [11]:
'''
数组的几种构造方法：
array, asarray, arrange, ones, ones_like, zeros, zeros_like, empty, empty_like, eye, identity
'''
I = np.eye(4)
print help(np.ones_like)
print "=========================================="
print np.ones_like(I)
print "=========================================="
print np.empty_like(I)

Help on function ones_like in module numpy.core.numeric:

ones_like(a, dtype=None, order='K', subok=True)
    Return an array of ones with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    
    Returns
    -------
    out : ndarray
     

In [14]:
'''
numpy 中的数据类型：
int(8/16/32/64) ,uint8(8/16/32/64); float(16/32/64/128); 
complex(64/128/256): 用两个32/64/128的浮点数表示复数
object: python对象类型
string_: 固定长度的字符串类型，每个字符一个字节
unicode_: 字节数由平台决定

类型的代码一般是首字母加数字，代表表示几个字节，如string 的S12表示12个字节的字符串
'''
unicode = np.array(['你好' '世界'],dtype=np.string_)
unicode

array(['\xe4\xbd\xa0\xe5\xa5\xbd\xe4\xb8\x96\xe7\x95\x8c'], 
      dtype='|S12')

In [21]:
# 通过np.astype显示地转换类型
x = np.arange(15,dtype=np.int32).reshape(3,5)
y= x.astype(np.float16) # astype无论如何都会copy原来地数组
x[1,2] = 111
print x
print y

[[  0   1   2   3   4]
 [  5   6 111   8   9]
 [ 10  11  12  13  14]]
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]]


In [22]:
# numpy地索引取值不是复制，而是原来的数据，因此任何在切片上的修改都会反映到原来的数组上
arr = np.arange(15)
slice = arr[5:7]
slice[0]=111
print arr,slice #两者都改变了

[  0   1   2   3   4 111   6   7   8   9  10  11  12  13  14] [111   6]


In [28]:
# 高维数组的表示，跟list的原理是一样的，不过此时对其中的值操作是原数组的视图，而不是复制产生的
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print x
print x[0],x[0][1],x[1][0][1]
x[0] = 123
print x

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]] [4 5 6] 8
[[[123 123 123]
  [123 123 123]]

 [[  7   8   9]
  [ 10  11  12]]]


In [36]:
# 布尔型索引
name = np.array(['a','b','c','d','a','d','f'])
rand = np.random.randn(7,5)
print rand,'\n'
print rand[name == 'b']
# 注意布尔型索引产生的数组都是复制产生的，即修改不会反映到原数组上
modify = rand[name == 'c']
modify[0] = 1111
print modify,'\n',rand #不会修改原来的值

print '\n',rand[name == 'c',2:]#将布尔型索引和切片混合使用

[[-0.20123193  0.88055563  0.11468052 -0.95847465  3.13229192]
 [ 1.2849999   0.77632153  1.14229352 -0.52535724 -0.49341735]
 [ 0.94788649 -0.59405155  0.15988572 -0.52333684 -0.80890649]
 [-0.51362432 -0.57799634  0.28953177 -0.61019054  0.93318739]
 [-0.99464018 -0.66045341 -0.21393372 -2.07697663  0.56306652]
 [-1.95275608 -0.93467029 -0.21167018 -0.26674793 -0.21503334]
 [ 0.92834168 -0.91018174  1.38480803  0.49519364  1.44584719]] 

[[ 1.2849999   0.77632153  1.14229352 -0.52535724 -0.49341735]]
[[ 1111.  1111.  1111.  1111.  1111.]] 
[[-0.20123193  0.88055563  0.11468052 -0.95847465  3.13229192]
 [ 1.2849999   0.77632153  1.14229352 -0.52535724 -0.49341735]
 [ 0.94788649 -0.59405155  0.15988572 -0.52333684 -0.80890649]
 [-0.51362432 -0.57799634  0.28953177 -0.61019054  0.93318739]
 [-0.99464018 -0.66045341 -0.21393372 -2.07697663  0.56306652]
 [-1.95275608 -0.93467029 -0.21167018 -0.26674793 -0.21503334]
 [ 0.92834168 -0.91018174  1.38480803  0.49519364  1.44584719]]

[[ 0.1598

In [50]:
# 花式索引(fancy indexing): 索引的时候不是传入一个数，而是传入一个列表或者ndarray.
x = np.arange(15).reshape(5,3)
print x,'\n'
print x[[1,2]],'\n',x[[-1,-4]]
# 如果传入的是多个列表则通过cartesion坐标定位元素
print x[[3,4],[0,1]] #选出x[3,0]和x[0,1]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[3 4 5]
 [6 7 8]] 
[[12 13 14]
 [ 3  4  5]]
[ 9 13]


In [63]:
# numpy的数组转置和轴交换,得到的都是原数组的视图
x = np.arange(16).reshape(4,4)
print x,'\n',x.T #只是简单的轴交换,不过没有改变原来的数组
print x.swapaxes(0,1)#对于二位数组，上述是等效的,不过此时x已经改变了
print '============================='
# transpose,输入是轴编号的元组
'''
轴的理解：就是每个元素所在的方向，从0开始
对于二维数组： axis = 0 代表row, axis=1 代表col
对于三维数组：借助分页的二维数组，axis = 0 代表页面， axis =1代表每页的行，axis=2代表每页的列
多维的无法视觉化，但是可以依次类推
'''
y = np.arange(16).reshape(2,2,4)
print y,'\n',y.transpose((0,2,1))#将每一页的row和col互换一下，输入的元组是要原数组要交换的axis

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [11]:
# ufunc 中的通用函数
'''
1:一元ufunc: abs,fabs,sqrt,square,isnan,isfinite,isinf,cos,cosh,arccos,logical_not(计算各元素的not)
2: 二元ufunc: add,subtract,power,maximum(fmax 相同，不过会忽略NaN),copysign(将第二个数组中的符号复制给第一个数组)
greater(greater_equal执行元素比较，产生布尔型数组)，logical_and,logical_or,logical_xor.
'''
#一元
x = np.arange(15)
print np.square(x),'\n'
print np.logical_not(x),'\n'
print np.isnan(x),'\n'
#二元
y = np.arange(15)
print np.add(x,y),'\n'
print np.greater_equal(x,y),'\n'
y = np.random.randn(15)
print y
print np.copysign(x,y),'\n'#将y的符号copy给x

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196] 

[ True False False False False False False False False False False False
 False False False] 

[False False False False False False False False False False False False
 False False False] 

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True] 

[ 0.62913249 -0.51994635 -0.76582095  0.98885177 -0.45668831  0.19037841
 -0.07892076  1.11070054  1.05469515 -0.34792328  1.25669726 -0.21878737
 -0.58074406 -0.35585132  0.01800239]
[  0.  -1.  -2.   3.  -4.   5.  -6.   7.   8.  -9.  10. -11. -12. -13.  14.] 

