In [2]:
import numpy as np

In [3]:
'''
二进制格式保存和存取文件
np.save():自动保存的文件后缀名是.npy
np.load(),

'''
#保存
x = np.arange(10)
np.save('local_text',x)
#读取
load = np.load('local_text.npy')
# 可以将多个数组压缩到一个文件,此时存贮的是key-value 对，key我们制定，value就是要保存的数据=>np.savez(),后缀名是.npz
y = np.arange(10,20)
np.savez('local_text.npz',a=x,b=y)
load = np.load('local_text.npz')
print load['a']
print load['b']

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [4]:
'''
Numpy.linalg 包中的常用函数：
diag(),dot(),trace(),det(),eig(),inv(),
pinv(): 矩阵的Moore-Penrose 伪逆
qr(): QR分解
svd(): SVD分解
solve():解决线性方程，其中Ax=B,A为方阵
lstsq(): Ax=b的最小二乘解
'''
import numpy.linalg as lin
A = np.arange(16).reshape(4,4)
print A,'\n'
print lin.svd(A),'\n'
print lin.lstsq(A,np.arange(4)),'\n'
print lin.solve(np.eye(3),np.arange(3)) #注意此时A必须是可逆的

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
       [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
       [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
       [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]), array([  3.51399637e+01,   2.27661021e+00,   8.80118491e-16,
         4.41188001e-17]), array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
       [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
       [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
       [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]])) 

(array([ 0.175,  0.1  ,  0.025, -0.05 ]), array([], dtype=float64), 2, array([  3.51399637e+01,   2.27661021e+00,   8.80118491e-16,
         4.41188001e-17])) 

[ 0.  1.  2.]


In [2]:
'''
numpy.random 的常用函数
permutation(), shuffle(),
rand():均匀分布
randint():给丁上下届范围的整数
randn()：标准正太分布
normal(): 正太分布
beta(), chisquare(),gamma()
'''
import numpy.random as npr
print npr.permutation(np.array([1,2,3,4])),'\n'
print npr.rand(2,6)
print npr.randint(2,10,size=(3,3)) #随机产生一个2～10的整数

[2 4 1 3] 

[[ 0.44361027  0.75286941  0.87531072  0.73828937  0.14678917  0.38214214]
 [ 0.40170213  0.75152173  0.53861686  0.50856886  0.53514185  0.2845727 ]]
[[5 6 2]
 [8 7 6]
 [6 2 4]]


In [5]:
'''
numpy 的repeat 和tile的区别：
repeat 是复制每一个元素，tile类似贴瓷砖，将原数组叠加
'''
x = np.random.randn(3,2)
print '原数组是',x,''
print '在axis = 0上repeat'
print x.repeat((2,1,2),axis=0),'\n'
print '在axis = 1上repeat'
print x.repeat((2,1),axis=1),'\n'

print '================='
print '将3*2数组的块转换成2*1'
print np.tile(x,(2,1)),'\n'
print '将3*2数组的块转换成3*2'
print np.tile(x,(3,2)),'\n'

在axis = 0上repeat
[[ 0.24562382  0.46778973]
 [ 0.24562382  0.46778973]
 [-0.20000563  0.44309756]
 [-0.32282027  0.01573574]
 [-0.32282027  0.01573574]] 

在axis = 1上repeat
[[ 0.24562382  0.24562382  0.46778973]
 [-0.20000563 -0.20000563  0.44309756]
 [-0.32282027 -0.32282027  0.01573574]] 

将3*2数组的块转换成2*1
[[ 0.24562382  0.46778973]
 [-0.20000563  0.44309756]
 [-0.32282027  0.01573574]
 [ 0.24562382  0.46778973]
 [-0.20000563  0.44309756]
 [-0.32282027  0.01573574]] 

将3*2数组的块转换成3*2
[[ 0.24562382  0.46778973  0.24562382  0.46778973]
 [-0.20000563  0.44309756 -0.20000563  0.44309756]
 [-0.32282027  0.01573574 -0.32282027  0.01573574]
 [ 0.24562382  0.46778973  0.24562382  0.46778973]
 [-0.20000563  0.44309756 -0.20000563  0.44309756]
 [-0.32282027  0.01573574 -0.32282027  0.01573574]
 [ 0.24562382  0.46778973  0.24562382  0.46778973]
 [-0.20000563  0.44309756 -0.20000563  0.44309756]
 [-0.32282027  0.01573574 -0.32282027  0.01573574]] 



In [2]:
'''
numpy 的vstack 和hstack：注意输入的是两个数组的一个元组，即np.hstack((y,z))
'''
y = np.random.randn(3,2)
z = np.random.randn(3,2)
print y
print z
print '--------hstack-----------'
print np.hstack((y,z))
print '--------vstack-----------'
print np.vstack((y,z))

[[ 1.01796405 -0.92267899]
 [-0.6160156  -0.33157541]
 [-0.87819031 -1.91307344]]
[[-1.84506886 -0.676116  ]
 [-2.33951832  0.35741981]
 [-1.96390415 -0.47755688]]
--------hstack-----------
[[ 1.01796405 -0.92267899 -1.84506886 -0.676116  ]
 [-0.6160156  -0.33157541 -2.33951832  0.35741981]
 [-0.87819031 -1.91307344 -1.96390415 -0.47755688]]
--------vstack-----------
[[ 1.01796405 -0.92267899]
 [-0.6160156  -0.33157541]
 [-0.87819031 -1.91307344]
 [-1.84506886 -0.676116  ]
 [-2.33951832  0.35741981]
 [-1.96390415 -0.47755688]]


In [12]:
'''
numpy 中得花式索引：take 和put
'''
#一维
x = np.arange(5)
print 'index is [2,4]'
print x.take([2,4])
print 'put [11,12] on index [0,1]'
x.put([0,1],[11,12])
print x
print '=================='
#二维, 可以自定义轴
print 'original array'
y = np.arange(12).reshape(3,4)
print y
print 'axis = 0, index=[1,3,1,3]'
print y.take([1,3,1,3])
print 'axis = 1, index=[1,3,1,3]'
print y.take([1,3,1,3],axis=1)

index is [2,4]
[2 4]
put [11,12] on index [0,1]
[11 12  2  3  4]
original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
axis = 0, index=[1,3,1,3]
[1 3 1 3]
axis = 1, index=[1,3,1,3]
[[ 1  3  1  3]
 [ 5  7  5  7]
 [ 9 11  9 11]]


In [ ]:
#this is the random test